### PR TITLE
Update installation instructions and developer guide in documentation; new community software, authors

### PR DESCRIPTION
**Pull request by gully**
💾 ➡️ 📑 😄

### CODE REVIEW

**Comment by gully** [comment]
@nksaunders can you investigate why the travis is failing due to a search_targetpixelfile problem?  Is that a MAST problem or something on our end?

**Comment by gully** [comment]
Hey all, I'm going to merge this unless there are objections.  It's all uncontroversial `.rst` for the documentation, which I've already made live.  I won't delete the branch, so reopen if something's wrong.  BTW, the travis is failing for some reason that doesn't have to do with the docs: it's a --remote_data flag issue. Strange.

**Comment by barentsen** [comment]
Thanks @gully!  All these changes look great and I have no requests for changes.

Before we merge, let me quickly try to re-run Travis.

**Comment by gully** [comment]
I added Dan's new package as a token commit (plus good new package), to trigger the Travis.

**Comment by barentsen** [comment]
All is good!  Must have been a temporary MAST issue.  Please go ahead and merge!

**Pull request merged**
