### PR TITLE
Short Cadence range slider for .interact()

### PR DESCRIPTION
**Pull request by gully**
Here is a working prototype of a short cadence range slider for interact aimed at Issue #465 .

This Pull Request realizes the dream of @nattieg, @ColinLittlefield, and @rrpastro, and may be of interest to @keatonb and others.

### CODE REVIEW

**Comment by gully** [comment]
20190321_lightkurve_sc_interact

**Comment by gully** [comment]
Neat feature of this mode:
If you pass in a long cadence lightcurve, it works the same as before-- no Display Window slider.
If you pass in a short cadence (or have more than `max_cadences=30000` kwarg), you automagically get a range slider.  You can exceed max_cadences by increasing the window size manually, but you will pay the price in latency.

**Comment by gully** [comment]
Update-- @barentsen recommends a data-decimation scheme to handle the performance issues of short cadence in `.interact()`.  The number of rendered data points would be reduced by showing 1-of-every-N-points, similar to the `.interact_bls()` approach from @christinahedges.  Zooming in would increase the fraction of points displayed.  There could also be synergies with datashader/holoviews, but these are likely beyond the scope of this PR, and may add more complexity.

**Comment by ColinLittlefield** [comment]
Thank you all for your work on this! The data-decimation scheme strikes me as an excellent solution. Do you have an estimate as to when this might become available? I have a student who's about to begin work on a short-cadence K2 light curve; she's become adept at using .interact(), so if possible, I'd like for her to be able to use the new feature.

**Comment by gully** [comment]
Hi @ColinLittlefield,
Thank you for staying engaged with the Issue, and for sharing lightkurve with your student!

Technically the window slider is available now if you follow the Step 1 guidelines in GitHub `command line instructions` link at the bottom of this pull request, and then follow the `development version installation` [instructions](http://docs.lightkurve.org/about/install.html#installing-the-development-version) in our documentation.  

In practice, this multi-step workaround may be counter productive if you're seeking a long-term stable solution.  I suspect it would be another 1-2 months for other developers to weigh-in on this feature, and they may decide not to merge the feature in the end depending on how much complexity it adds to the long-term maintenance of the code base.

Feel free to email our [helpdesk](https://keplerscience.arc.nasa.gov/helpdesk.html) with details of your use-case to help raise the visibility of the issue with a wider group of decision makers.

**Comment by gully** [comment]
Update: @barentsen and I discussed an option to seamlessly update the data with the bokeh-native zoom and scroll tools (the wheel zoom and box zoom, for example).

**Comment by gully** [comment]
Update here: I noticed that bokeh offers support for "level of detail" scaling:

https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#controlling-level-of-detail

It may be worth looking into setting a level-of-detail threshold to make the performance better for short cadence lightcurves.

**Comment by barentsen** [comment]
I'm going to close this for now because we are running out of person power to finish and support new features, but I hope someone will be able to pick this up in the future!!  It looks great!

**Pull request closed without merging**
