### PR TITLE
Add a tutorial for `KeplerTargetPixelFile.interact()`

### PR DESCRIPTION
**Pull request by barentsen**
I removed the `KeplerTargetPixelFile.interact()` tutorial from master because it did not compile into sphinx (issue #120).  @gully can you look into refactoring it in a way that it can be compiled into the docs?

### CODE REVIEW

**Comment by gully** [comment]
Ok, this tutorial has replaced the widgets with gifs so they can work in the docs.

**Comment by gully** [comment]
Should be ready for merge when desired.

**Comment by gully** [comment]
Update: We wish to provide the gif files locally, rather than rely on an internet connection.  We should be able to place the gif files in the `docs/source/_static/images` directory.  We should then be able to access these images with a relative import from within a Jupyter notebook:

```ipython
In [1]  ! pwd
          lightkurve/docs/source/tutorials
```

```ipython
          ![Animated Gif Demo](../_static/images/tpf_interact.gif)
```
Yields a missing figure link
[❓]

If I copy the gif file to the local Jupyter notebook, or a child directory, the gif animation appears as desired:

```ipython
          ![Animated Gif Demo](tpf_interact.gif)
```
*works*

```ipython
          ![Animated Gif Demo](images/tpf_interact.gif)
```
*works*

It seems like a permissions issue-- child files can be accessed, but not files in parent directories.  I observe the same behavior with html's `` syntax.  I propose introducing a new directory `images` within `lightkurve/docs/source/tutorials`:

**Comment by barentsen** [comment]
Thanks @gully!  I made two very minor changes:
- Renamed title to `Interactively inspecting Target Pixel Files and Lightcurves` to better fit in amongst the other tutorials in the Table Of Contents.
- I removed the final sentence to fit into the style of the other tutorials (it said: `We hope you enjoy the .interact() tool!  Requests for extensions or more features are welcomed on our GitHub Issues.`) 

Otherwise this is great!! Merging!

**Pull request merged**
