### PR TITLE
SFF tutorial

### PR DESCRIPTION
**Pull request by mirca**
This PR adds our steps into reproducing some figures in Vanderburg's SFF paper.

I think this is important specially to inform newcomers about the products of our tools.

### CODE REVIEW

**Comment by gully** [comment]
Looks good from my perspective.  I really like that we mimic the Vanderburg & Johnson figures exactly, in form and content.  This makes a head-to-head comparison very clear and concise, and demystifies what we are doing.  Bravo!

**Comment by mirca** [comment]
@gully I couldn't agree more

**Comment by barentsen** [comment]
This looks like a fantastic tutorial!  This will make a great item in an "advanced" section of the tutorials in which we dig into why and how certain algorithms work.

I'd recommend including more sentences throughout the notebook to actually explain what the code is doing.  It's very readable to us, but I'm worried more novice users are going to struggle.  It's not a top-priority though, so I'm happy for this to be merged as-is!

**Comment by mirca** [comment]
@barentsen I think you made some changes to this notebook. Absolutely no rush to push them, I'm just writing this as a remainder.

**Comment by mirca** [comment]
this has been done in #45

**Pull request closed without merging**
