### PR TITLE
Rolling Band Tutorial

### PR DESCRIPTION
**Pull request by christinahedges**
I added this rolling band tutorial. It might need tweaking to make sure that the embedded youtube video loads properly when the ipynb file is turned into rst.

### CODE REVIEW

**Comment by christinahedges** [comment]
@barentsen can you please take a look at the video embedding? Thanks

**Comment by christinahedges** [comment]
I remember now, this won't work until we make from_archive have a search radius.

**Comment by barentsen** [comment]
@christinahedges Would it be hard to turn the video into an animated gif?

**Comment by christinahedges** [comment]
Nope I can do that, no problem

**Comment by barentsen** [comment]
This is a really good tutorial!  My only main comment is that the following sentence:

`It looks like the signal is still there in the background pixels. Unfortunately this means the signal is not astrophysical.`

Should be more something like:

`It looks like the signal is present in the background pixels with the same amplitude.  The Kepler PSF has a typical width of N pixels and so we would expect the amplitude of the signal to be much weaker in the background pixels that neighbor the star. To get a definitive answer, let's investigate whether the signal is present in the background pixels in a nearby target that is sufficiently far away from the star...`

**Comment by christinahedges** [comment]
Lavly, I'll add this.

**Comment by christinahedges** [comment]
rollingband

**Comment by christinahedges** [comment]
@barentsen this is ready for review!

**Comment by christinahedges** [comment]
@barentsen can we merge this?

**Comment by christinahedges** [comment]
@barentsen this is why I merge my own pull requests.

**Comment by barentsen** [comment]
Thanks @christinahedges!  This tutorial is really useful.  I made a few very minor style edits and added the tutorial to the index.  This is ready to merge now.

Note: we are going to have to update this tutorial if we implement `tpf.conesearch` as part of #138.

**Pull request merged**
