### PR TITLE
Add UserWarning for time=NaN warning in LightCurve and added tests

### PR DESCRIPTION
**Pull request by JoseALermaIII**
Added a `UserWarning` to the time=NaN warning portion of the LightCurve constructor in lightcurve.py so that tests could be added to test_lightcurve.py

### CODE REVIEW

**Comment by JoseALermaIII** [comment]
I think I can test the logging portion using pytest's decorators (if I read the docs correctly). I'll try it out tomorrow

**Comment by JoseALermaIII** [comment]
You got it! I'll check out Astropy's warning class to see which portions are relevant, add it, and remove the call to `logging.warning`.

**Comment by barentsen** [comment]
Thanks @JoseALermaIII!  I think the definition of `LightkurveWarning` will simply be:
```
class LightkurveWarning(Warning):
    pass
```

**Comment by JoseALermaIII** [comment]
Astropy's warning system has a custom `AstropyUserWarning` class for `UserWarning`s that inherits from `AstropyWarning`. 

Since we are keeping the warning classes simple for now, I implemented the `LightkurveWarning` class in `lightcurve.py` and added a test for the `LightkurveWarning` class in `test_utils.py`

**Comment by barentsen** [comment]
Thank you @JoseALermaIII !!

**Pull request merged**
