### PR TITLE
[WIP] Make PRF fitting prior more flexible to account for spacecraft movement

### PR DESCRIPTION
**Pull request by gully**
Work in progress.
Relates to Issue #95

### CODE REVIEW

**Comment by gully** [comment]
We are seeing that sometimes the results of PRF fitting can be outside the allowed prior window.  That result cannot be, so something is wrong.  

- [ ] Identify cause of result-out-of-prior-window bug
- [ ] Identify and eliminate, or simply suppress the warnings that occur during PRF fitting.  Perhaps provide a log of fails at the end of the fitting procedure.
- [ ] The `cadences=` subset kwarg does not seem to work due to a reshape error at the end of fitting.

**Comment by christinahedges** [comment]
@amcody and @barentsen would like to refactor this slightly to make PRFphotometry part of SceneModel. Then the call would be

`SceneModel(...).fit()`

**Comment by christinahedges** [comment]
Having talked with @amcody we're going to remove the new functions `ra_dec_to_uniformprior`, `ra_dec_to_gaussprior` and `stars_to_prior` from this PR and move them to a new PR which will fix #137. 

This PR will now only address the time varying motion priors from poscorr, and we'll have a new one for ra/dec priors.

**Comment by christinahedges** [comment]
* Some campaigns that have not been reprocessed and so have no POSCORR (campaign 9) and so we will have to default to something else
* There is currently no way to give a static prior. This might not be a particularly useful case?

**Comment by christinahedges** [comment]
Currently I am still having the same issue as before, where the fit is now extending outside of the bounds.

**Comment by barentsen** [comment]
I'm closing this PR because it is stale (>1 yr old) and because we haven't had time to actively improve the PRF photometry sub-package.  Of course the PR will still be here for future reference re PRF photometry improvements, which would be awesome!

**Pull request closed without merging**
