### PR TITLE
Overhaul the tutorials, improve directory structure visibility, add new content, link headers

### PR DESCRIPTION
**Pull request by gully**
Targeted at issue #268, and discussion therein.

### CODE REVIEW

**Comment by gully** [comment]
Based on some recent discussions, I'm going to push forward with removing the numbering system of the tutorials.  I'm also going to move the tutorials to the main landing page on GitHub repo, with modified Makefile for the docs.  I propose the docs get re-rendered with dpi=300 or higher to suit high resolution (e.g. Retina) displays.  I also added a README that will render on GitHub with clickable links.  I will also add headers that can be clicked on in the documentation pages.

**Comment by gully** [comment]
OK, I've renamed the tutorials with a compromise: the topical themes are grouped by number, and notebooks are left unsorted within theme, when navigating locally.  The README.md file and doc Table of Contents remain sorted within the theme based on our prescribed ordering.

```bash
$ ls -1
01-lightcurve-files.ipynb
01-target-pixel-files.ipynb
01-using-the-periodogram-class.ipynb
01-what-are-lightcurves.ipynb
02-how-to-make-a-supernova-lightcurve.ipynb
02-how-to-recover-the-first-tess-candidate.ipynb
02-how-to-use-lightkurve-for-asteroseismology.ipynb
02-recover-a-planet.ipynb
03-appending-lightcurves.ipynb
03-cutting-out-tpfs-from-tess-ffis.ipynb
03-how-to-use-prf-photometry.ipynb
03-making-custom-apertures.ipynb
03-making-fits-files.ipynb
04-how-to-detrend.ipynb
04-identify-rolling-band.ipynb
04-interact-with-lightcurves-and-tpf.ipynb
04-removing-cbvs.ipynb
04-replicate-vanderburg-2014-k2sff.ipynb
04-replicate-vanderburg-2014-lightkurve.ipynb
README.md
```

**Comment by gully** [comment]
The `02-how-to-use-lightkurve-for-asteroseismology` tutorial takes a really long time to run, since it's doing multiple SFF corrections on a short cadence lightcurve.  I kept getting timeout warnings while running the notebook, and finally resolved it by [updating](https://nbsphinx.readthedocs.io/en/0.2.7/timeout.html) the `conf.py` file in `docs/source`

**Comment by gully** [comment]
In the "how to recover a planet" tutorial, I updated the dependence on `transit_periodogram` in favor of the astropy 3.1 implementation of BoxLeastSquares.
The "make a tpf from FFI" tutorial breaks on `make notebooks` because it expects a `data` directory with fits files in it.  I propose we use packaged or fetched files to demo the from_fits method.  I also propose extending this tutorial to include how to get TPFs from TESS-CUT produced tpfs.

**Comment by barentsen** [comment]
Thanks for all these improvements @gully!  I think the solution to the "make a tpf from FFI" tutorial breaking is to include a `!wget something` cell.  We wouldn't want to package large FFI's.

**Comment by barentsen** [comment]
Thanks for this PR @gully!  Your changes to `conf.py` look good and I like the new `README.md` and the renaming of files. 

It looks like we have a merge conflict with three tutorials.  I think we applied bug fixes to those since the first commit in this PR (e.g. we recently renamed `phase` into `transit_midpoint` as an argument of `lc.fold()`).  I'm not sure that rebasing will work in this case because the notebooks have been re-executed?

Once you fix the merge conflict I'm happy to glance over the notebook changes (because I need to learn how `BoxLeastSquares` works myself =)) and merge this!

**Comment by barentsen** [comment]
Ping @gully -- can you resolve the merge conflict?  I'd love to merge this!

**Comment by gully** [comment]
Regarding the merge conflicts:

1. 2.03-appending-lightcurves 

 ✅ Update transit_midpoint from "phase" in fold kwarg

```bash
$ diff master_version.ipynb new.ipynb
diff --git a/master_version.ipynb b/new.ipynb
index da0197f..3943a9d 100644
--- a/master_version.ipynb
+++ b/new.ipynb
@@ -125,7 +125,7 @@
   "metadata": {},
   "outputs": [],
   "source": [
    "lc.fold(3.52254, transit_midpoint=0.38).bin().scatter();"phase=0.38).bin().scatter();"
   ]
  }
 ],
```

2. 2.05-making-custom-apertures
 ✅ Replace for "quarter"... loops with `tpfs = search_targetpixelfile(kic).download_all()`
 ✅ Fix transit_midpoint again

3. how-to-recover-the-first-tess-candidate
 ✅ Fix transit_midpoint again

**Comment by gully** [comment]
The `cutting-out-tpfs-from-tess-ffis` tutorial should be re-worked to make it run from scratch without additional pre-fetching of data

**Comment by gully** [comment]
I spot checked the `make notebooks` produced content, and the headers appear fine on the html pages.  The hardcoded links will work once the PR is merged.

header

ready for review!

**Pull request merged**
