### PR TITLE
docfix: document flux_column for read / download ; also cleanup quality mask

### PR DESCRIPTION
**Pull request by orionlee**
Partially address #846,  by documenting `flux_column` in read / download so that `SAP_FLUX` can be normalized.

### CODE REVIEW

**Comment by orionlee** [comment]
In `KeplerLightCurve.read()`, it defaults to `Kepler` format, does that mean if one tries to read, say, a K2SFF lightcurve, one has to specify the `format` explicitly?

In download codepath, it seems to be able to detect different filetype variants and switch accordingly.

https://github.com/KeplerGO/lightkurve/blob/v2.0b1/lightkurve/io/read.py#L65

**Review by barentsen — APPROVED** [review]
Thanks @orionlee. This looks like an excellent docs improvement. :+1:

**Comment by barentsen** [comment]
> In KeplerLightCurve.read(), it defaults to Kepler format, does that mean if one tries to read, say, a K2SFF lightcurve, one has to specify the format explicitly?

Correct.  I suppose it would be a useful enhancement to automatically detect the file format inside `KeplerLightCurve.read()` as well.

Both the docstring and file format detection were/are missing from those class methods because I've wanted to advertise the generic `lk.read()` function as the main interface to open a path, but of course that shouldn't stop us from making the `LightCurve.read()` methods as user-friendly as possible.

**Comment by orionlee** [comment]
> I've wanted to advertise the generic `lk.read()` function as the main interface to open a path.

I didn't realize `lk.read()` is meant to be a public API - currently it is not listed. :-(

We should probably then properly expose and document `lk.read`.

**Comment by orionlee** [comment]
I tried to expose `lk.read()` in api doc, but don't know sphinx enough to make it so - I can only expose the actual `lk.io.read()`.

**Comment by barentsen** [comment]
@orionlee I've been working on a few tutorials which will feature it, and before releasing v2.0, I intend to revisit the API docs page to make sure all those key functions are prominently listed.  (Don't let that stop you from making the awesome improvements you made in this PR!  They benefit the API page directly, of course!)

**Pull request merged**
