### PR TITLE
Improved CBV corrector

### PR DESCRIPTION
**Pull request by christinahedges**
CBV corrector can now be passed a light curve, so if you have a `KeplerLightCurve` you've edited, you can run a CBV correction on it.

Also allows you to pass in your own CBV array and use them for a correction.

### CODE REVIEW

**Comment by barentsen** [comment]
Thank you @christinahedges!  This does of course change the existing API.  Does anyone see downsides/caveats in that?  /cc @mirca

**Comment by mirca** [comment]
This looks good to me.  But it seems that there are some changes that seems to belong to different PRs like the changes in `lightkurve/targetpixelfile.py`.

**Comment by barentsen** [comment]
I did a `git rebase master` so we can test this PR against the new Azure tests.  Fingers crossed!

**Comment by barentsen** [comment]
This looks good to merge!  Thank you @christinahedges!!

**Pull request merged**
