### PR TITLE
Suppress warnings during tests

### PR DESCRIPTION
**Pull request by gully**
This PR is aimed at suppressing warnings when running the unit test.  See Issues #586, #585, and others.

### CODE REVIEW

**Comment by gully** [comment]
This warning suppression is going great!  Thanks @texadactyl for guiding us to these issues.

I'm having trouble running the "raise error on warning trick" that @barentsen showed me for the special case of `RuntimeWarning`.  What API tree hierarchy should I replace in the `????` placeholder?

`py.test -v test_targetpixelfile.py -W error::????.RuntimeWarning`

**Comment by gully** [comment]
By the way, the coverage is almost guaranteed to drop because we are now avoiding warnings in the first place.  The strategy to raise coverage should be to [catch the warnings](https://docs.pytest.org/en/latest/warnings.html#warns) with pytest, which I've done only sparingly in this work so far.

**Comment by gully** [comment]
Hey @barentsen this PR is a step in the right direction and future-proofs some now-failing tests due to TESS data making Kepler-10 have more search results than before.  It's not 100% silencing all warnings, and it drops the coverage significantly.

**Comment by gully** [comment]
Quick check of `py.test` with no remote data

**master** 117 passed, 47 skipped, 25 warnings in 17.38 seconds
**this PR** 118 passed, 47 skipped, 13 warnings in 17.78 seconds

**Comment by barentsen** [comment]
Thanks @gully!  This is all look spiffy! :+1:

**Comment by texadactyl** [comment]
@gully @barentsen 

My only concern is that by suppressing warnings (normally highly inadvisable) about log() or sqrt() failures, the test in question is not completing the intended exercize.  If you are confident that this is not the case, then okay.  

As I have said before, I understand that you folks are primarily scientists and need to prioritize your time.

**Comment by barentsen** [comment]
@texadactyl Agreed, we have to be very careful with silencing `RuntimeWarning` messages related to math operations.  (And if we silence them, we need to have sufficient inline comments explaining why it is appropriate if at all.)

Fortunately the ~12 warnings that were fixed by this PR are unrelated to e.g. log or sqrt failures.  Those `RuntimeWarnings` are amongst the ~13 warnings that still remained after this PR was merged.

**Pull request merged**
