### PR TITLE
[WIP] Updated SFF tutorial, now split into two notebooks

### PR DESCRIPTION
**Pull request by gully**
Tasks to do:

- [x] Add more explanatory material.
- [x] Use same TPF aperture mask as VDB & J.
- [x] Lop off the same time stamps as VDB & J
- [ ] Use the same thruster fire masks as VDB & J.
- [ ] Use the `lc.correct()` method instead of the `SFF` directly.
- [x] Suppress warning while plotting.
- [x] Make screencast

### CODE REVIEW

**Comment by gully** [comment]
ping @christinahedges here is the tutorial PR

**Comment by gully** [comment]
OK, I overhauled these and made screencasts:

- Replicating Vanderburg & Johnson 2014 
https://www.youtube.com/watch?v=3Vs9uWW-E84

- Replicating Vanderburg & Johnson 2014 with lightkurve
https://www.youtube.com/watch?v=kYRqZwz2VPU&t=108s

**Comment by gully** [comment]
These are ready for review

**Comment by gully** [comment]
ok, now rebased!

**Comment by barentsen** [comment]
This looks really great, thanks @gully!!  I'm going to merge this now ahead of tess.ninja.

**Pull request merged**
