### PR TITLE
Add a `from_fits` method to TargetPixelFile and LightCurveFile

### LINKED ISSUE #192: Add a from_file() function to load FITS lightcurve file
#### Problem description
Attempting to use lightkurve to read in a FITS lightcurve file (e.g., ktwo246802680-c13_llc.fits), it was not straightforward in the documentation/tutorials how to do it. I suggest adding a from_file() function to mirror the well-documented w/ example from_archive() function.

#### Example

By asking staff, I was able to use the following commands to load a lightcurve file, but I did not see it as an example in the documentation.

```python
from lightkurve import KeplerLightCurveFile
lcf = KeplerLightCurveFile("ktwo246802680-c13_llc.fits")
```

I think if there was a from_file() function, it would be more obvious that a user that could load using from_archive() or from_file():

```python
from lightkurve import KeplerLightCurveFile
lcf = KeplerLightCurveFile.from_file("ktwo246802680-c13_llc.fits")
```

#### Expected behavior
Expect intro tutorial to show how to load from a local file as well as the archive.

#### Environment:
Linux
1.0b9
pip

### PR DESCRIPTION
**Pull request by barentsen**
This resolves #192.

It will require changes to the docs which have already been started (#172 & PR #176).

@JeffLCoughlin Can you review?

### CODE REVIEW

**Comment by mirca** [comment]
@barentsen I was thinking whether it would be more appropriate to add ``from_fits`` at the base class ``TargetPixelFile``? The advantage being that you wouldn't have to copy the code to ``TessTargetPixelFile`` and could also reuse part of the docstring.

**Comment by barentsen** [comment]
@mirca Agreed!  ...however I couldn't figure out how to call the constructor of the subclass from a method in the parent class?  (But I was doing this on a plane so I couldn't Google.)

**Comment by barentsen** [comment]
Working towards the next pip release today.  Merging...

**Comment by mirca** [comment]
Very nice!

**Comment by JeffLCoughlin** [comment]
Sorry I missed seeing the review until now, but this is awesome!  Thanks for tackling so quick.

**Pull request merged**
