### PR TITLE
Change the documentation layout (new sphinx theme)

### PR DESCRIPTION
**Pull request by barentsen**
I propose to change the layout of the Lightkurve docs to start using a more minimalist design which makes it easier to navigate to the four key components of the documentation: *Quickstart*, *Tutorials*, *API*, and *About* (the latter will include developer docs).

The preview version is online here: https://barentsen.github.io/lightkurve/

I would love for folks to have a very critical look at the words, presentation, etc!

#### New front page

screenshot from 2019-01-28 10-03-24

#### New tutorials page

screenshot from 2019-01-28 10-03-44

#### New API docs overview

screenshot from 2019-01-28 10-04-05

### CODE REVIEW

**Comment by barentsen** [comment]
@gully Would you be willing to review and merge this PR?

**Comment by gully** [comment]
OMG this is so good.  I adore this theme, such an intuitive, sleek, and inviting experience.

The word "install" does not appear on the landing page, it is under the `About` heading.  Admittedly, not too hard to surmise that installation instructions are most likely in the about section. (after spending more than 5 seconds with the page, no problem here).

Really, I can't find any demerits, this improvement to the docs would make @jonathansick proud, I think.

**Comment by gully** [comment]
Merging in :3: :2: 🥇

**Comment by barentsen** [comment]
The prominent `Quickstart` button takes you to a page that starts with installation instructions.  I was wondering if there should be a separate `Install` button next to `Quickstart`, or if `Quickstart` is intuitive enough as the only place you need to go to get up and running. Thoughts?

**Comment by jonathansick** [comment]
love it! well done.

**Comment by gully** [comment]
I would recommend adding a link in the Quickstart tutorial indicating that there are alternatives to pip, so something like:

> simply install the latest stable release of the lightkurve package using pip...
*or see the [installation guide](lightkurve-docs/html/about/install.html) for conda or development versions.*

**Pull request merged**
