### PR TITLE
A Bokeh Widget to Interactively Find Planets with BLS

### PR DESCRIPTION
**Pull request by christinahedges**
## What is it?

I've made us a tool to interactively find planets using BLS. The key features of the tool are

* Live view of BLS, light curve and folded light curve, with models overlayed
* Fast rendering of BLS, because of adaptive resolution. The BLS renders each time the user zooms in, to a specified resolution. This makes the tool very fast to work with, even when there are lots of points in the light curve.
* Works with Kepler, K2 and TESS light curves. This tool will work even for a full 4 year Kepler light curve.

## How does it work?

```python
import lightkurve as lk
lc = lk.search_lightcurvefile('kepler-10', quarter=3).download()
lc = lc.PDCSAP_FLUX.normalize().remove_nans().flatten()
lc.interact_bls()
```
image

## To Do:

- [x] Moar unit tests
- [ ] Add a tutorial for how to use the tool in a notebook
- [ ] Create a video tutorial

## Future

* Look into using HoloViews to render the light curve and folded light curve to make the widget even faster.

### CODE REVIEW

**Comment by nksaunders** [comment]
**Bug**: occasionally bokeh plotting tools (at the bottom right of each bokeh plot) will disappear, severely limiting functionality of this widget. This is easily resolved by rerunning the cell, and may or may not be worth investigating further.

**Comment by christinahedges** [comment]
Gully's feedback:
- Make help more conspicuous
- New buttons make warnings

**Comment by barentsen** [comment]
Awesome!! Thank you @christinahedges :+1: :+1: :+1:

Merging in 3 ... 2 ...

**Comment by mrtommyb** [comment]
I guess I'll make an issue.

**Pull request merged**
