### PR TITLE
Adding extra_columns attribute to LightCurve objects

### PR DESCRIPTION
**Pull request by dfm**
This proposal adds a more general interface for having extra columns of data in a light curve that should be propagated through copies, appends, and subscripts. The existing implementation is brittle and adding a new column (for example as a subclass) is hard. This pull request should reproduce the current behavior, but simplify the procedure for adding new columns. This would lay the ground work for #713.

Note: it's not ready to merge yet (needs some tests!) but I wanted to post it here for feedback in the meantime.

### CODE REVIEW

**Comment by barentsen** [comment]
@dfm I like this PR a lot. Thank you!! :+1:

Strengths of this PR:
* it makes the LightCurve class hierarchy more generic and consistent through fairly minor changes;
* it does not alter existing behavior;
* none of the changes prevent us from adopting an `astropy.TimeSeries`-based table solution in the future, should we wish to go down that (more complicated) route.

**Question**: how will this PR address #713?  In #713, we identified that there are certain single-valued attributes (e.g. `exposure_time`, `sector`, `mission`, `camera`) which could be thought of as columns when different light curves are stitched together.  Merging this PR would not enable these attributes to be treated as columns (yet?) because `extra_columns` is a hard-coded class property.  This PR does enable columns to be added by sub-classing `LightCurve`, is that the idea?

**Comment by dfm** [comment]
Thanks! And yes, that's exactly what I'm doing in another project. This feature makes it much easier to implement subclasses without reimplementing things like the append method. 

It's worth noting that this doesn't quite duplicate the existing behavior in append. Now, it'll throw a warning if any of the light curves are missing any extra columns and returns more sensible results. Previously, the results of append would actually be really funky if any of the lc objects didn't have all the same columns. You would end up with things like cadenceno not being the same length as time. This is only a hypothetical currently because TESS and Kepler light curves have all the same extra columns, but this won't always be true for subclasses.

**Comment by barentsen** [comment]
Thanks again @dfm!

I plan to add a few commits here today to add a test for the new behavior of `append`, to make sure `warnings.warn` uses type `LightkurveWarning`, and to add a change log entry. Other than that, this should be good to merge!

**Comment by barentsen** [comment]
Oops, I don't seem able to push to this branch!

**Comment by dfm** [comment]
Are you sure? You should be able to!

**Comment by barentsen** [comment]
@dfm You're right!  Epic fail on my part!

**Comment by dfm** [comment]
More like EPIC amirite?

**Comment by barentsen** [comment]
Yes. More like ... EPIC. You are right!

**Pull request merged**
