### PR TITLE
Introduce a default logger to lightkurve

### PR DESCRIPTION
**Pull request by barentsen**
This PR simplifies logging by introducing a default logger. (Addresses #145.)

### CODE REVIEW

**Comment by barentsen** [comment]
The purpose of this PR is to avoid having to have `verbose` arguments.  Instead, to make lightkurve verbose you'd execute:
```
lightkurve.log.setLevel('DEBUG')
```
and to make it quiet you'd execute:
```
lightkurve.log.setLevel('ERROR')
```

For example, this will be silent:
```
lcf = KeplerLightCurveFile.from_archive('Kepler-10', quarter=10)
```

And this will print astroquery's message:
```
lightkurve.log.setLevel('INFO')
lcf = KeplerLightCurveFile.from_archive('Kepler-10', quarter=10)
```

**Comment by mirca** [comment]
This looks good to me! Thanks for this much awaited feature, @barentsen!
[This test](https://github.com/KeplerGO/lightkurve/pull/150/files#diff-3a6a2a90043504098a17134931dd25f9R147) is failing on Windows, though.

**Comment by barentsen** [comment]
Actually the failing test shouldn't run on Appveyor because we should add the `@pytest.mark.remote_data` decorator, but that doesn't explain why it's failing.  I can't figure out why it's different in Windows!

**Comment by mirca** [comment]
Thanks 👍

**Comment by christinahedges** [comment]
This looks great, much better way to message users. Thanks @barentsen!

**Pull request merged**
